# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Teqnavi-Admin"
client_id = "94b7433443be5e84e0e06ebbfe875a6d"
application_url = "https://luxury-unlike-marina-combined.trycloudflare.com"
embedded = true
handle = "teqnavi-admin"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teqnavi-demo-store-1.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,read_script_tags,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://luxury-unlike-marina-combined.trycloudflare.com/auth/callback",
  "https://luxury-unlike-marina-combined.trycloudflare.com/auth/shopify/callback",
  "https://luxury-unlike-marina-combined.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://luxury-unlike-marina-combined.trycloudflare.com"
subpath = "pages"
prefix = "a"

[pos]
embedded = false
